### ISSUE TITLE
«Class Rokanthemes\Brand\Model\Brandlist does not exist»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [royalwholesalecandy/core#126]
Similar to https://github.com/royalwholesalecandy/core/issues/106

**Comment by dmitrii-fediuk** [comment]
I deleted the block 219

![2020-01-02_15-51-09](https://user-images.githubusercontent.com/83204/71661213-b89ee280-2d77-11ea-96ee-1b0a8d26bfdd.png)

**Comment by dmitrii-fediuk** [comment]
```
DELETE FROM eav_attribute WHERE 'product_brand' = attribute_code;
```

**Comment by alainstout** [comment]
Thanks it worked
