### ISSUE TITLE
`Magenest_QuickBooksDesktop`: «Function 'connectionError' doesn't exist» in vendor/magento/zendframework1/library/Zend/Soap/Server.php

### ISSUE THREAD

**Issue by dmitrii-fediuk** [royalwholesalecandy/core#36]

**Comment by dmitrii-fediuk** [comment]
Fixed in `app/code/Magenest/QuickBooksDesktop/WebConnector/Handlers.php`.

**Comment by Morgon** [comment]
You are the only mention of this particular issue. Can you elaborate on what you changed in the Magenest module? They're not exactly the most responsive bunch.

**Comment by dmitrii-fediuk** [comment]
You can hire me in Upwork for it: https://www.upwork.com/fl/mage2pro
I will not support you for free.

**Comment by Morgon** [comment]
Great, thanks for the reply. I get wanting to make a living, but demanding payment just to give a small (and undoubtedly quick) explanation of how you corrected an odd issue is objectively ridiculous, _especially_ with the curt way you responded. Merry Christmas to you, as well!
